import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/navbar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-7xl mx-auto`}
      >
        <Navbar />
        {children}
        <button className="fixed right-5 top-1/2 -translate-y-1/2 -rotate-90 origin-right bg-accent text-white text-sm font-medium px-4 py-2 rounded-t-lg cursor-pointer hover:bg-accent/80 transition z-50">
          Book Consulting
        </button>
      </body>
    </html>
  );
}
